#!/bin/sh

set -ex

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

APP_NAME="_APP_NAME_"
TEMPLATE_SSL="/usr/share/${APP_NAME}-apache2/templates/web-ssl"
TEMPLATE_RAW="/usr/share/${APP_NAME}-apache2/templates/web-raw"
OUTPUT="/etc/apache2/sites-available/${APP_NAME}"

# source debconf library
. /usr/share/debconf/confmodule

case "$1" in

  configure)

    db_get ${APP_NAME}/server/autoinstall

    if [ "$RET" = "false" ]; then
      exit 0
    else
      db_get ${APP_NAME}/server/hostname
      web_hostname="$RET"

      db_get ${APP_NAME}/server/ssl
      web_ssl="$RET"

      db_get ${APP_NAME}/server/ssl_cert
      web_ssl_cert="$RET"

      db_get ${APP_NAME}/server/ssl_key
      web_ssl_key="$RET"

      db_get ${APP_NAME}/server/ssl_ca
      web_ssl_ca="$RET"

      # make it a config variable
      web_ssl_port="443"
      web_raw_port="80"
      web_app_port=$(${APP_NAME} config:get PORT || echo "6000")

      if [ "$web_ssl" = "true" ]; then
	template="$TEMPLATE_SSL"
	a2enmod ssl
      else
	template="$TEMPLATE_RAW"
      fi

      tmpfile=$(mktemp)
      cp -f "$template" "$tmpfile"

      sed -i "s|_HOSTNAME_|${web_hostname}|g" ${tmpfile}
      sed -i "s|_SSL_CERT_|${web_ssl_cert}|g" ${tmpfile}
      sed -i "s|_SSL_KEY_|${web_ssl_key}|g" ${tmpfile}
      sed -i "s|_SSL_CA_|${web_ssl_ca}|g" ${tmpfile}
      sed -i "s|_SSL_PORT_|${web_ssl_port}|g" ${tmpfile}
      sed -i "s|_RAW_PORT_|${web_raw_port}|g" ${tmpfile}
      sed -i "s|_APP_PORT_|${web_app_port}|g" ${tmpfile}

      mv -f "$tmpfile" "$OUTPUT"
      chmod 0640 "$OUTPUT"

      a2enmod proxy_http headers expires
      a2dissite default
      a2ensite "${APP_NAME}"
      service apache2 reload

    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

